name: Clone hidden-public repository, get repository information, and create a new branch

on:
  push:
    branches: [main]

jobs:
  clone-get-info-create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone hidden-public repository
      run: |
        git clone https://github.com/org-1394820934/hidden-public.git
        cd hidden-public

    - name: Get repository information
      run: |
        org_name="org-1394820934"
        repo_name="hidden-public"
        repo_info=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$org_name/$repo_name)
        echo "$repo_info"

    - name: Create new branch
      run: |
        org_name="org-1394820934"
        repo_name="hidden-public"
        base_branch="main"
        new_branch="new-branch"
        new_branch_sha=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$org_name/$repo_name/git/ref/heads/$base_branch | jq -r .object.sha)
        new_branch_ref=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$org_name/$repo_name/git/refs -X POST -d "{\"ref\":\"refs/heads/$new_branch\",\"sha\":\"$new_branch_sha\"}")
        echo "$new_branch_ref"
