name: Clone hidden-public repository and get repository information

on:
  push:
    branches: [main]

jobs:
  clone-and-get-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone hidden-public repository
      run: |
        git clone https://github.com/org-1394820934/hidden-public.git
        cd hidden-public

    - name: Get repository information
      run: |
        org_name="org-1394820934"
        repo_info=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/$org_name/repos)
        echo "$repo_info"
