name: Clone hidden-public repository, get repository information, and create a new branch

on:
  push:
    branches: [main]

jobs:
  clone-get-info-create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone hidden-public repository
      run: |
        git clone https://github.com/org-1394820934/repo-1.git
        cd repo-1

    - name: Get repository information
      run: |
        org_name="org-1394820934"
        repo_name="hidden-public"
        repo_info=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$org_name/$repo_name)
        echo "$repo_info"
