name: Clone hidden-public repository, get repository information, and create a new branch

on:
  push:
    branches: [main]

jobs:
  clone-get-info-create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone hidden-public repository
      run: |
        git clone https://github.com/org-1394820934/hidden-public.git
        cd hidden-public

    - name: Get repository information
      run: |
        org_name="org-1394820934"
        repo_info=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/$org_name/repos)
        echo "$repo_info"

    - name: Create new branch
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Create new branch'
        branch: 'new-branch'
        title: 'New Branch'
        body: 'This is a new branch.'
        base: 'main'
