name: Clone hidden-public repository, get repository information, and create a new issue

on:
  push:
    branches: [main]

jobs:
  clone-get-info-create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone hidden-public repository
      run: |
        git clone https://github.com/org-1394820934/hidden-public.git
        cd hidden-public

    - name: Get repository information
      run: |
        org_name="org-1394820934"
        repo_info=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/$org_name/repos)
        echo "$repo_info"

    - name: Create new issue
      env:
        REPO_OWNER: "org-1394820934"
        REPO_NAME: "hidden-public"
        ISSUE_TITLE: "New issue"
        ISSUE_BODY: "This is a new issue"
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues \
          -d '{"title": "'"$ISSUE_TITLE"'", "body": "'"$ISSUE_BODY"'"}'
